use_frameworks!
platform :ios, '9.0'
#忽略.cocoapods中多个specs源引起的警告问题
#install! 'cocoapods', :warn_for_unused_master_specs_repo => false, :deterministic_uuids=>false
target 'WNPlayerPlus_Example' do
  pod 'WNPlayerPlus', :path => '../'
end
